package br.com.fiap.gs.model;

public enum ODS {
    ODS_1_ERRADICACAO_DA_POBREZA,
    ODS_2_FOME_ZERO,
    ODS_3_SAUDE_E_BEM_ESTAR,
    ODS_4_EDUCACAO_DE_QUALIDADE,
    ODS_5_IGUALDADE_DE_GENERO,
    ODS_6_AGUA_POTAVEL,
    ODS_7_ENERGIA_LIMPA,
    ODS_8_TRABALHO_DIGNO,
    ODS_9_INDUSTRIA_E_INOVACAO,
    ODS_10_REDUCAO_DAS_DESIGUALDADES,
    ODS_11_CIDADES_SUSTENTAVEIS,
    ODS_12_CONSUMO_RESPONSAVEL,
    ODS_13_ACAO_CONTRA_CLIMA,
    ODS_14_VIDA_NA_AGUA,
    ODS_15_VIDA_TERRESTRE,
    ODS_16_PAZ_E_JUSTICA,
    ODS_17_PARCERIAS
}
